[package]
name = "ollama-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
ollama-rs = "0.2.2"
tokio = { version = "1", features = ["full"] }
